---
# Initial ZTP connection - Set password on factory-reset switch

- name: (ztp_init_connection) Configure initial password on factory switch
  aoscx_ztp_auth:
    hostname: "{{ ansible_host }}"
    username: admin
    password: "{{ aruba_password }}"
  delegate_to: localhost
  when: aruba_password is defined
